/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UsersRouteImport } from './routes/users'
import { Route as UserRouteImport } from './routes/user'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as RedirectRouteImport } from './routes/redirect'
import { Route as PostsRouteImport } from './routes/posts'
import { Route as HomeRouteImport } from './routes/home'
import { Route as DeferredRouteImport } from './routes/deferred'
import { Route as CustomScriptDotjsRouteImport } from './routes/customScript[.]js'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as PathlessLayoutRouteImport } from './routes/_pathlessLayout'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UsersIndexRouteImport } from './routes/users.index'
import { Route as RoomIndexRouteImport } from './routes/room/index'
import { Route as QuizzesIndexRouteImport } from './routes/quizzes/index'
import { Route as PostsIndexRouteImport } from './routes/posts.index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as AssignmentsIndexRouteImport } from './routes/assignments/index'
import { Route as UsersUserIdRouteImport } from './routes/users.$userId'
import { Route as ShareShareIdRouteImport } from './routes/share/$shareId'
import { Route as QuizzesNewRouteImport } from './routes/quizzes/new'
import { Route as PostsPostIdRouteImport } from './routes/posts.$postId'
import { Route as DashboardDriveRouteImport } from './routes/dashboard/drive'
import { Route as AssignmentsAssignmentIdRouteImport } from './routes/assignments/$assignmentId'
import { Route as ApiUsersRouteImport } from './routes/api/users'
import { Route as ApiAssignmentsRouteImport } from './routes/api/assignments'
import { Route as PathlessLayoutNestedLayoutRouteImport } from './routes/_pathlessLayout/_nested-layout'
import { Route as RoomRoomIdIndexRouteImport } from './routes/room/$roomId/index'
import { Route as DashboardDriveIndexRouteImport } from './routes/dashboard/drive/index'
import { Route as PostsPostIdDeepRouteImport } from './routes/posts_.$postId.deep'
import { Route as DashboardClassroomsNewRouteImport } from './routes/dashboard/classrooms/new'
import { Route as DashboardClassroomsClassIdRouteImport } from './routes/dashboard/classrooms/$classId'
import { Route as ApiUsersUserIdRouteImport } from './routes/api/users.$userId'
import { Route as ApiRoomRoomIdRouteImport } from './routes/api/room/$roomId'
import { Route as ApiQuizzesMediaRouteImport } from './routes/api/quizzes/media'
import { Route as ApiDriveMediaRouteImport } from './routes/api/drive/media'
import { Route as ApiDriveFoldersRouteImport } from './routes/api/drive/folders'
import { Route as ApiAuthSignInRouteImport } from './routes/api/auth/sign-in'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiAdminStatsRouteImport } from './routes/api/admin/stats'
import { Route as PathlessLayoutNestedLayoutRouteBRouteImport } from './routes/_pathlessLayout/_nested-layout/route-b'
import { Route as PathlessLayoutNestedLayoutRouteARouteImport } from './routes/_pathlessLayout/_nested-layout/route-a'
import { Route as ApiShareShareIdQrRouteImport } from './routes/api/share/$shareId/qr'
import { Route as ApiDriveMediaIdRouteImport } from './routes/api/drive/media/$id'
import { Route as ApiDriveFoldersIdRouteImport } from './routes/api/drive/folders/$id'

const UsersRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)
const UserRoute = UserRouteImport.update({
  id: '/user',
  path: '/user',
  getParentRoute: () => rootRouteImport,
} as any)
const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const RedirectRoute = RedirectRouteImport.update({
  id: '/redirect',
  path: '/redirect',
  getParentRoute: () => rootRouteImport,
} as any)
const PostsRoute = PostsRouteImport.update({
  id: '/posts',
  path: '/posts',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const DeferredRoute = DeferredRouteImport.update({
  id: '/deferred',
  path: '/deferred',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomScriptDotjsRoute = CustomScriptDotjsRouteImport.update({
  id: '/customScript.js',
  path: '/customScript.js',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const PathlessLayoutRoute = PathlessLayoutRouteImport.update({
  id: '/_pathlessLayout',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersIndexRoute = UsersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => UsersRoute,
} as any)
const RoomIndexRoute = RoomIndexRouteImport.update({
  id: '/room/',
  path: '/room/',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizzesIndexRoute = QuizzesIndexRouteImport.update({
  id: '/quizzes/',
  path: '/quizzes/',
  getParentRoute: () => rootRouteImport,
} as any)
const PostsIndexRoute = PostsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PostsRoute,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const AssignmentsIndexRoute = AssignmentsIndexRouteImport.update({
  id: '/assignments/',
  path: '/assignments/',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersUserIdRoute = UsersUserIdRouteImport.update({
  id: '/$userId',
  path: '/$userId',
  getParentRoute: () => UsersRoute,
} as any)
const ShareShareIdRoute = ShareShareIdRouteImport.update({
  id: '/share/$shareId',
  path: '/share/$shareId',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizzesNewRoute = QuizzesNewRouteImport.update({
  id: '/quizzes/new',
  path: '/quizzes/new',
  getParentRoute: () => rootRouteImport,
} as any)
const PostsPostIdRoute = PostsPostIdRouteImport.update({
  id: '/$postId',
  path: '/$postId',
  getParentRoute: () => PostsRoute,
} as any)
const DashboardDriveRoute = DashboardDriveRouteImport.update({
  id: '/dashboard/drive',
  path: '/dashboard/drive',
  getParentRoute: () => rootRouteImport,
} as any)
const AssignmentsAssignmentIdRoute = AssignmentsAssignmentIdRouteImport.update({
  id: '/assignments/$assignmentId',
  path: '/assignments/$assignmentId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUsersRoute = ApiUsersRouteImport.update({
  id: '/api/users',
  path: '/api/users',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAssignmentsRoute = ApiAssignmentsRouteImport.update({
  id: '/api/assignments',
  path: '/api/assignments',
  getParentRoute: () => rootRouteImport,
} as any)
const PathlessLayoutNestedLayoutRoute =
  PathlessLayoutNestedLayoutRouteImport.update({
    id: '/_nested-layout',
    getParentRoute: () => PathlessLayoutRoute,
  } as any)
const RoomRoomIdIndexRoute = RoomRoomIdIndexRouteImport.update({
  id: '/room/$roomId/',
  path: '/room/$roomId/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardDriveIndexRoute = DashboardDriveIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardDriveRoute,
} as any)
const PostsPostIdDeepRoute = PostsPostIdDeepRouteImport.update({
  id: '/posts_/$postId/deep',
  path: '/posts/$postId/deep',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardClassroomsNewRoute = DashboardClassroomsNewRouteImport.update({
  id: '/dashboard/classrooms/new',
  path: '/dashboard/classrooms/new',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardClassroomsClassIdRoute =
  DashboardClassroomsClassIdRouteImport.update({
    id: '/dashboard/classrooms/$classId',
    path: '/dashboard/classrooms/$classId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiUsersUserIdRoute = ApiUsersUserIdRouteImport.update({
  id: '/$userId',
  path: '/$userId',
  getParentRoute: () => ApiUsersRoute,
} as any)
const ApiRoomRoomIdRoute = ApiRoomRoomIdRouteImport.update({
  id: '/api/room/$roomId',
  path: '/api/room/$roomId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiQuizzesMediaRoute = ApiQuizzesMediaRouteImport.update({
  id: '/api/quizzes/media',
  path: '/api/quizzes/media',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDriveMediaRoute = ApiDriveMediaRouteImport.update({
  id: '/api/drive/media',
  path: '/api/drive/media',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDriveFoldersRoute = ApiDriveFoldersRouteImport.update({
  id: '/api/drive/folders',
  path: '/api/drive/folders',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSignInRoute = ApiAuthSignInRouteImport.update({
  id: '/api/auth/sign-in',
  path: '/api/auth/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminStatsRoute = ApiAdminStatsRouteImport.update({
  id: '/api/admin/stats',
  path: '/api/admin/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const PathlessLayoutNestedLayoutRouteBRoute =
  PathlessLayoutNestedLayoutRouteBRouteImport.update({
    id: '/route-b',
    path: '/route-b',
    getParentRoute: () => PathlessLayoutNestedLayoutRoute,
  } as any)
const PathlessLayoutNestedLayoutRouteARoute =
  PathlessLayoutNestedLayoutRouteARouteImport.update({
    id: '/route-a',
    path: '/route-a',
    getParentRoute: () => PathlessLayoutNestedLayoutRoute,
  } as any)
const ApiShareShareIdQrRoute = ApiShareShareIdQrRouteImport.update({
  id: '/api/share/$shareId/qr',
  path: '/api/share/$shareId/qr',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDriveMediaIdRoute = ApiDriveMediaIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiDriveMediaRoute,
} as any)
const ApiDriveFoldersIdRoute = ApiDriveFoldersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiDriveFoldersRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/customScript.js': typeof CustomScriptDotjsRoute
  '/deferred': typeof DeferredRoute
  '/home': typeof HomeRoute
  '/posts': typeof PostsRouteWithChildren
  '/redirect': typeof RedirectRoute
  '/reports': typeof ReportsRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/user': typeof UserRoute
  '/users': typeof UsersRouteWithChildren
  '/api/assignments': typeof ApiAssignmentsRoute
  '/api/users': typeof ApiUsersRouteWithChildren
  '/assignments/$assignmentId': typeof AssignmentsAssignmentIdRoute
  '/dashboard/drive': typeof DashboardDriveRouteWithChildren
  '/posts/$postId': typeof PostsPostIdRoute
  '/quizzes/new': typeof QuizzesNewRoute
  '/share/$shareId': typeof ShareShareIdRoute
  '/users/$userId': typeof UsersUserIdRoute
  '/assignments': typeof AssignmentsIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/posts/': typeof PostsIndexRoute
  '/quizzes': typeof QuizzesIndexRoute
  '/room': typeof RoomIndexRoute
  '/users/': typeof UsersIndexRoute
  '/route-a': typeof PathlessLayoutNestedLayoutRouteARoute
  '/route-b': typeof PathlessLayoutNestedLayoutRouteBRoute
  '/api/admin/stats': typeof ApiAdminStatsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/auth/sign-in': typeof ApiAuthSignInRoute
  '/api/drive/folders': typeof ApiDriveFoldersRouteWithChildren
  '/api/drive/media': typeof ApiDriveMediaRouteWithChildren
  '/api/quizzes/media': typeof ApiQuizzesMediaRoute
  '/api/room/$roomId': typeof ApiRoomRoomIdRoute
  '/api/users/$userId': typeof ApiUsersUserIdRoute
  '/dashboard/classrooms/$classId': typeof DashboardClassroomsClassIdRoute
  '/dashboard/classrooms/new': typeof DashboardClassroomsNewRoute
  '/posts/$postId/deep': typeof PostsPostIdDeepRoute
  '/dashboard/drive/': typeof DashboardDriveIndexRoute
  '/room/$roomId': typeof RoomRoomIdIndexRoute
  '/api/drive/folders/$id': typeof ApiDriveFoldersIdRoute
  '/api/drive/media/$id': typeof ApiDriveMediaIdRoute
  '/api/share/$shareId/qr': typeof ApiShareShareIdQrRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/customScript.js': typeof CustomScriptDotjsRoute
  '/deferred': typeof DeferredRoute
  '/home': typeof HomeRoute
  '/redirect': typeof RedirectRoute
  '/reports': typeof ReportsRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/user': typeof UserRoute
  '/api/assignments': typeof ApiAssignmentsRoute
  '/api/users': typeof ApiUsersRouteWithChildren
  '/assignments/$assignmentId': typeof AssignmentsAssignmentIdRoute
  '/posts/$postId': typeof PostsPostIdRoute
  '/quizzes/new': typeof QuizzesNewRoute
  '/share/$shareId': typeof ShareShareIdRoute
  '/users/$userId': typeof UsersUserIdRoute
  '/assignments': typeof AssignmentsIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/posts': typeof PostsIndexRoute
  '/quizzes': typeof QuizzesIndexRoute
  '/room': typeof RoomIndexRoute
  '/users': typeof UsersIndexRoute
  '/route-a': typeof PathlessLayoutNestedLayoutRouteARoute
  '/route-b': typeof PathlessLayoutNestedLayoutRouteBRoute
  '/api/admin/stats': typeof ApiAdminStatsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/auth/sign-in': typeof ApiAuthSignInRoute
  '/api/drive/folders': typeof ApiDriveFoldersRouteWithChildren
  '/api/drive/media': typeof ApiDriveMediaRouteWithChildren
  '/api/quizzes/media': typeof ApiQuizzesMediaRoute
  '/api/room/$roomId': typeof ApiRoomRoomIdRoute
  '/api/users/$userId': typeof ApiUsersUserIdRoute
  '/dashboard/classrooms/$classId': typeof DashboardClassroomsClassIdRoute
  '/dashboard/classrooms/new': typeof DashboardClassroomsNewRoute
  '/posts/$postId/deep': typeof PostsPostIdDeepRoute
  '/dashboard/drive': typeof DashboardDriveIndexRoute
  '/room/$roomId': typeof RoomRoomIdIndexRoute
  '/api/drive/folders/$id': typeof ApiDriveFoldersIdRoute
  '/api/drive/media/$id': typeof ApiDriveMediaIdRoute
  '/api/share/$shareId/qr': typeof ApiShareShareIdQrRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_pathlessLayout': typeof PathlessLayoutRouteWithChildren
  '/admin': typeof AdminRoute
  '/customScript.js': typeof CustomScriptDotjsRoute
  '/deferred': typeof DeferredRoute
  '/home': typeof HomeRoute
  '/posts': typeof PostsRouteWithChildren
  '/redirect': typeof RedirectRoute
  '/reports': typeof ReportsRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/user': typeof UserRoute
  '/users': typeof UsersRouteWithChildren
  '/_pathlessLayout/_nested-layout': typeof PathlessLayoutNestedLayoutRouteWithChildren
  '/api/assignments': typeof ApiAssignmentsRoute
  '/api/users': typeof ApiUsersRouteWithChildren
  '/assignments/$assignmentId': typeof AssignmentsAssignmentIdRoute
  '/dashboard/drive': typeof DashboardDriveRouteWithChildren
  '/posts/$postId': typeof PostsPostIdRoute
  '/quizzes/new': typeof QuizzesNewRoute
  '/share/$shareId': typeof ShareShareIdRoute
  '/users/$userId': typeof UsersUserIdRoute
  '/assignments/': typeof AssignmentsIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/posts/': typeof PostsIndexRoute
  '/quizzes/': typeof QuizzesIndexRoute
  '/room/': typeof RoomIndexRoute
  '/users/': typeof UsersIndexRoute
  '/_pathlessLayout/_nested-layout/route-a': typeof PathlessLayoutNestedLayoutRouteARoute
  '/_pathlessLayout/_nested-layout/route-b': typeof PathlessLayoutNestedLayoutRouteBRoute
  '/api/admin/stats': typeof ApiAdminStatsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/auth/sign-in': typeof ApiAuthSignInRoute
  '/api/drive/folders': typeof ApiDriveFoldersRouteWithChildren
  '/api/drive/media': typeof ApiDriveMediaRouteWithChildren
  '/api/quizzes/media': typeof ApiQuizzesMediaRoute
  '/api/room/$roomId': typeof ApiRoomRoomIdRoute
  '/api/users/$userId': typeof ApiUsersUserIdRoute
  '/dashboard/classrooms/$classId': typeof DashboardClassroomsClassIdRoute
  '/dashboard/classrooms/new': typeof DashboardClassroomsNewRoute
  '/posts_/$postId/deep': typeof PostsPostIdDeepRoute
  '/dashboard/drive/': typeof DashboardDriveIndexRoute
  '/room/$roomId/': typeof RoomRoomIdIndexRoute
  '/api/drive/folders/$id': typeof ApiDriveFoldersIdRoute
  '/api/drive/media/$id': typeof ApiDriveMediaIdRoute
  '/api/share/$shareId/qr': typeof ApiShareShareIdQrRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/customScript.js'
    | '/deferred'
    | '/home'
    | '/posts'
    | '/redirect'
    | '/reports'
    | '/sign-in'
    | '/sign-up'
    | '/user'
    | '/users'
    | '/api/assignments'
    | '/api/users'
    | '/assignments/$assignmentId'
    | '/dashboard/drive'
    | '/posts/$postId'
    | '/quizzes/new'
    | '/share/$shareId'
    | '/users/$userId'
    | '/assignments'
    | '/dashboard'
    | '/posts/'
    | '/quizzes'
    | '/room'
    | '/users/'
    | '/route-a'
    | '/route-b'
    | '/api/admin/stats'
    | '/api/auth/$'
    | '/api/auth/sign-in'
    | '/api/drive/folders'
    | '/api/drive/media'
    | '/api/quizzes/media'
    | '/api/room/$roomId'
    | '/api/users/$userId'
    | '/dashboard/classrooms/$classId'
    | '/dashboard/classrooms/new'
    | '/posts/$postId/deep'
    | '/dashboard/drive/'
    | '/room/$roomId'
    | '/api/drive/folders/$id'
    | '/api/drive/media/$id'
    | '/api/share/$shareId/qr'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/customScript.js'
    | '/deferred'
    | '/home'
    | '/redirect'
    | '/reports'
    | '/sign-in'
    | '/sign-up'
    | '/user'
    | '/api/assignments'
    | '/api/users'
    | '/assignments/$assignmentId'
    | '/posts/$postId'
    | '/quizzes/new'
    | '/share/$shareId'
    | '/users/$userId'
    | '/assignments'
    | '/dashboard'
    | '/posts'
    | '/quizzes'
    | '/room'
    | '/users'
    | '/route-a'
    | '/route-b'
    | '/api/admin/stats'
    | '/api/auth/$'
    | '/api/auth/sign-in'
    | '/api/drive/folders'
    | '/api/drive/media'
    | '/api/quizzes/media'
    | '/api/room/$roomId'
    | '/api/users/$userId'
    | '/dashboard/classrooms/$classId'
    | '/dashboard/classrooms/new'
    | '/posts/$postId/deep'
    | '/dashboard/drive'
    | '/room/$roomId'
    | '/api/drive/folders/$id'
    | '/api/drive/media/$id'
    | '/api/share/$shareId/qr'
  id:
    | '__root__'
    | '/'
    | '/_pathlessLayout'
    | '/admin'
    | '/customScript.js'
    | '/deferred'
    | '/home'
    | '/posts'
    | '/redirect'
    | '/reports'
    | '/sign-in'
    | '/sign-up'
    | '/user'
    | '/users'
    | '/_pathlessLayout/_nested-layout'
    | '/api/assignments'
    | '/api/users'
    | '/assignments/$assignmentId'
    | '/dashboard/drive'
    | '/posts/$postId'
    | '/quizzes/new'
    | '/share/$shareId'
    | '/users/$userId'
    | '/assignments/'
    | '/dashboard/'
    | '/posts/'
    | '/quizzes/'
    | '/room/'
    | '/users/'
    | '/_pathlessLayout/_nested-layout/route-a'
    | '/_pathlessLayout/_nested-layout/route-b'
    | '/api/admin/stats'
    | '/api/auth/$'
    | '/api/auth/sign-in'
    | '/api/drive/folders'
    | '/api/drive/media'
    | '/api/quizzes/media'
    | '/api/room/$roomId'
    | '/api/users/$userId'
    | '/dashboard/classrooms/$classId'
    | '/dashboard/classrooms/new'
    | '/posts_/$postId/deep'
    | '/dashboard/drive/'
    | '/room/$roomId/'
    | '/api/drive/folders/$id'
    | '/api/drive/media/$id'
    | '/api/share/$shareId/qr'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PathlessLayoutRoute: typeof PathlessLayoutRouteWithChildren
  AdminRoute: typeof AdminRoute
  CustomScriptDotjsRoute: typeof CustomScriptDotjsRoute
  DeferredRoute: typeof DeferredRoute
  HomeRoute: typeof HomeRoute
  PostsRoute: typeof PostsRouteWithChildren
  RedirectRoute: typeof RedirectRoute
  ReportsRoute: typeof ReportsRoute
  SignInRoute: typeof SignInRoute
  SignUpRoute: typeof SignUpRoute
  UserRoute: typeof UserRoute
  UsersRoute: typeof UsersRouteWithChildren
  ApiAssignmentsRoute: typeof ApiAssignmentsRoute
  ApiUsersRoute: typeof ApiUsersRouteWithChildren
  AssignmentsAssignmentIdRoute: typeof AssignmentsAssignmentIdRoute
  DashboardDriveRoute: typeof DashboardDriveRouteWithChildren
  QuizzesNewRoute: typeof QuizzesNewRoute
  ShareShareIdRoute: typeof ShareShareIdRoute
  AssignmentsIndexRoute: typeof AssignmentsIndexRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  QuizzesIndexRoute: typeof QuizzesIndexRoute
  RoomIndexRoute: typeof RoomIndexRoute
  ApiAdminStatsRoute: typeof ApiAdminStatsRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiAuthSignInRoute: typeof ApiAuthSignInRoute
  ApiDriveFoldersRoute: typeof ApiDriveFoldersRouteWithChildren
  ApiDriveMediaRoute: typeof ApiDriveMediaRouteWithChildren
  ApiQuizzesMediaRoute: typeof ApiQuizzesMediaRoute
  ApiRoomRoomIdRoute: typeof ApiRoomRoomIdRoute
  DashboardClassroomsClassIdRoute: typeof DashboardClassroomsClassIdRoute
  DashboardClassroomsNewRoute: typeof DashboardClassroomsNewRoute
  PostsPostIdDeepRoute: typeof PostsPostIdDeepRoute
  RoomRoomIdIndexRoute: typeof RoomRoomIdIndexRoute
  ApiShareShareIdQrRoute: typeof ApiShareShareIdQrRoute
}

declare module '@tanstack/solid-router' {
  interface FileRoutesByPath {
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user': {
      id: '/user'
      path: '/user'
      fullPath: '/user'
      preLoaderRoute: typeof UserRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/redirect': {
      id: '/redirect'
      path: '/redirect'
      fullPath: '/redirect'
      preLoaderRoute: typeof RedirectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/posts': {
      id: '/posts'
      path: '/posts'
      fullPath: '/posts'
      preLoaderRoute: typeof PostsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deferred': {
      id: '/deferred'
      path: '/deferred'
      fullPath: '/deferred'
      preLoaderRoute: typeof DeferredRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customScript.js': {
      id: '/customScript.js'
      path: '/customScript.js'
      fullPath: '/customScript.js'
      preLoaderRoute: typeof CustomScriptDotjsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_pathlessLayout': {
      id: '/_pathlessLayout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof PathlessLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users/': {
      id: '/users/'
      path: '/'
      fullPath: '/users/'
      preLoaderRoute: typeof UsersIndexRouteImport
      parentRoute: typeof UsersRoute
    }
    '/room/': {
      id: '/room/'
      path: '/room'
      fullPath: '/room'
      preLoaderRoute: typeof RoomIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quizzes/': {
      id: '/quizzes/'
      path: '/quizzes'
      fullPath: '/quizzes'
      preLoaderRoute: typeof QuizzesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/posts/': {
      id: '/posts/'
      path: '/'
      fullPath: '/posts/'
      preLoaderRoute: typeof PostsIndexRouteImport
      parentRoute: typeof PostsRoute
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assignments/': {
      id: '/assignments/'
      path: '/assignments'
      fullPath: '/assignments'
      preLoaderRoute: typeof AssignmentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users/$userId': {
      id: '/users/$userId'
      path: '/$userId'
      fullPath: '/users/$userId'
      preLoaderRoute: typeof UsersUserIdRouteImport
      parentRoute: typeof UsersRoute
    }
    '/share/$shareId': {
      id: '/share/$shareId'
      path: '/share/$shareId'
      fullPath: '/share/$shareId'
      preLoaderRoute: typeof ShareShareIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quizzes/new': {
      id: '/quizzes/new'
      path: '/quizzes/new'
      fullPath: '/quizzes/new'
      preLoaderRoute: typeof QuizzesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/posts/$postId': {
      id: '/posts/$postId'
      path: '/$postId'
      fullPath: '/posts/$postId'
      preLoaderRoute: typeof PostsPostIdRouteImport
      parentRoute: typeof PostsRoute
    }
    '/dashboard/drive': {
      id: '/dashboard/drive'
      path: '/dashboard/drive'
      fullPath: '/dashboard/drive'
      preLoaderRoute: typeof DashboardDriveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assignments/$assignmentId': {
      id: '/assignments/$assignmentId'
      path: '/assignments/$assignmentId'
      fullPath: '/assignments/$assignmentId'
      preLoaderRoute: typeof AssignmentsAssignmentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/users': {
      id: '/api/users'
      path: '/api/users'
      fullPath: '/api/users'
      preLoaderRoute: typeof ApiUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/assignments': {
      id: '/api/assignments'
      path: '/api/assignments'
      fullPath: '/api/assignments'
      preLoaderRoute: typeof ApiAssignmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_pathlessLayout/_nested-layout': {
      id: '/_pathlessLayout/_nested-layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof PathlessLayoutNestedLayoutRouteImport
      parentRoute: typeof PathlessLayoutRoute
    }
    '/room/$roomId/': {
      id: '/room/$roomId/'
      path: '/room/$roomId'
      fullPath: '/room/$roomId'
      preLoaderRoute: typeof RoomRoomIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/drive/': {
      id: '/dashboard/drive/'
      path: '/'
      fullPath: '/dashboard/drive/'
      preLoaderRoute: typeof DashboardDriveIndexRouteImport
      parentRoute: typeof DashboardDriveRoute
    }
    '/posts_/$postId/deep': {
      id: '/posts_/$postId/deep'
      path: '/posts/$postId/deep'
      fullPath: '/posts/$postId/deep'
      preLoaderRoute: typeof PostsPostIdDeepRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/classrooms/new': {
      id: '/dashboard/classrooms/new'
      path: '/dashboard/classrooms/new'
      fullPath: '/dashboard/classrooms/new'
      preLoaderRoute: typeof DashboardClassroomsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/classrooms/$classId': {
      id: '/dashboard/classrooms/$classId'
      path: '/dashboard/classrooms/$classId'
      fullPath: '/dashboard/classrooms/$classId'
      preLoaderRoute: typeof DashboardClassroomsClassIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/users/$userId': {
      id: '/api/users/$userId'
      path: '/$userId'
      fullPath: '/api/users/$userId'
      preLoaderRoute: typeof ApiUsersUserIdRouteImport
      parentRoute: typeof ApiUsersRoute
    }
    '/api/room/$roomId': {
      id: '/api/room/$roomId'
      path: '/api/room/$roomId'
      fullPath: '/api/room/$roomId'
      preLoaderRoute: typeof ApiRoomRoomIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/quizzes/media': {
      id: '/api/quizzes/media'
      path: '/api/quizzes/media'
      fullPath: '/api/quizzes/media'
      preLoaderRoute: typeof ApiQuizzesMediaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/drive/media': {
      id: '/api/drive/media'
      path: '/api/drive/media'
      fullPath: '/api/drive/media'
      preLoaderRoute: typeof ApiDriveMediaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/drive/folders': {
      id: '/api/drive/folders'
      path: '/api/drive/folders'
      fullPath: '/api/drive/folders'
      preLoaderRoute: typeof ApiDriveFoldersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/sign-in': {
      id: '/api/auth/sign-in'
      path: '/api/auth/sign-in'
      fullPath: '/api/auth/sign-in'
      preLoaderRoute: typeof ApiAuthSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/stats': {
      id: '/api/admin/stats'
      path: '/api/admin/stats'
      fullPath: '/api/admin/stats'
      preLoaderRoute: typeof ApiAdminStatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_pathlessLayout/_nested-layout/route-b': {
      id: '/_pathlessLayout/_nested-layout/route-b'
      path: '/route-b'
      fullPath: '/route-b'
      preLoaderRoute: typeof PathlessLayoutNestedLayoutRouteBRouteImport
      parentRoute: typeof PathlessLayoutNestedLayoutRoute
    }
    '/_pathlessLayout/_nested-layout/route-a': {
      id: '/_pathlessLayout/_nested-layout/route-a'
      path: '/route-a'
      fullPath: '/route-a'
      preLoaderRoute: typeof PathlessLayoutNestedLayoutRouteARouteImport
      parentRoute: typeof PathlessLayoutNestedLayoutRoute
    }
    '/api/share/$shareId/qr': {
      id: '/api/share/$shareId/qr'
      path: '/api/share/$shareId/qr'
      fullPath: '/api/share/$shareId/qr'
      preLoaderRoute: typeof ApiShareShareIdQrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/drive/media/$id': {
      id: '/api/drive/media/$id'
      path: '/$id'
      fullPath: '/api/drive/media/$id'
      preLoaderRoute: typeof ApiDriveMediaIdRouteImport
      parentRoute: typeof ApiDriveMediaRoute
    }
    '/api/drive/folders/$id': {
      id: '/api/drive/folders/$id'
      path: '/$id'
      fullPath: '/api/drive/folders/$id'
      preLoaderRoute: typeof ApiDriveFoldersIdRouteImport
      parentRoute: typeof ApiDriveFoldersRoute
    }
  }
}

interface PathlessLayoutNestedLayoutRouteChildren {
  PathlessLayoutNestedLayoutRouteARoute: typeof PathlessLayoutNestedLayoutRouteARoute
  PathlessLayoutNestedLayoutRouteBRoute: typeof PathlessLayoutNestedLayoutRouteBRoute
}

const PathlessLayoutNestedLayoutRouteChildren: PathlessLayoutNestedLayoutRouteChildren =
  {
    PathlessLayoutNestedLayoutRouteARoute:
      PathlessLayoutNestedLayoutRouteARoute,
    PathlessLayoutNestedLayoutRouteBRoute:
      PathlessLayoutNestedLayoutRouteBRoute,
  }

const PathlessLayoutNestedLayoutRouteWithChildren =
  PathlessLayoutNestedLayoutRoute._addFileChildren(
    PathlessLayoutNestedLayoutRouteChildren,
  )

interface PathlessLayoutRouteChildren {
  PathlessLayoutNestedLayoutRoute: typeof PathlessLayoutNestedLayoutRouteWithChildren
}

const PathlessLayoutRouteChildren: PathlessLayoutRouteChildren = {
  PathlessLayoutNestedLayoutRoute: PathlessLayoutNestedLayoutRouteWithChildren,
}

const PathlessLayoutRouteWithChildren = PathlessLayoutRoute._addFileChildren(
  PathlessLayoutRouteChildren,
)

interface PostsRouteChildren {
  PostsPostIdRoute: typeof PostsPostIdRoute
  PostsIndexRoute: typeof PostsIndexRoute
}

const PostsRouteChildren: PostsRouteChildren = {
  PostsPostIdRoute: PostsPostIdRoute,
  PostsIndexRoute: PostsIndexRoute,
}

const PostsRouteWithChildren = PostsRoute._addFileChildren(PostsRouteChildren)

interface UsersRouteChildren {
  UsersUserIdRoute: typeof UsersUserIdRoute
  UsersIndexRoute: typeof UsersIndexRoute
}

const UsersRouteChildren: UsersRouteChildren = {
  UsersUserIdRoute: UsersUserIdRoute,
  UsersIndexRoute: UsersIndexRoute,
}

const UsersRouteWithChildren = UsersRoute._addFileChildren(UsersRouteChildren)

interface ApiUsersRouteChildren {
  ApiUsersUserIdRoute: typeof ApiUsersUserIdRoute
}

const ApiUsersRouteChildren: ApiUsersRouteChildren = {
  ApiUsersUserIdRoute: ApiUsersUserIdRoute,
}

const ApiUsersRouteWithChildren = ApiUsersRoute._addFileChildren(
  ApiUsersRouteChildren,
)

interface DashboardDriveRouteChildren {
  DashboardDriveIndexRoute: typeof DashboardDriveIndexRoute
}

const DashboardDriveRouteChildren: DashboardDriveRouteChildren = {
  DashboardDriveIndexRoute: DashboardDriveIndexRoute,
}

const DashboardDriveRouteWithChildren = DashboardDriveRoute._addFileChildren(
  DashboardDriveRouteChildren,
)

interface ApiDriveFoldersRouteChildren {
  ApiDriveFoldersIdRoute: typeof ApiDriveFoldersIdRoute
}

const ApiDriveFoldersRouteChildren: ApiDriveFoldersRouteChildren = {
  ApiDriveFoldersIdRoute: ApiDriveFoldersIdRoute,
}

const ApiDriveFoldersRouteWithChildren = ApiDriveFoldersRoute._addFileChildren(
  ApiDriveFoldersRouteChildren,
)

interface ApiDriveMediaRouteChildren {
  ApiDriveMediaIdRoute: typeof ApiDriveMediaIdRoute
}

const ApiDriveMediaRouteChildren: ApiDriveMediaRouteChildren = {
  ApiDriveMediaIdRoute: ApiDriveMediaIdRoute,
}

const ApiDriveMediaRouteWithChildren = ApiDriveMediaRoute._addFileChildren(
  ApiDriveMediaRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PathlessLayoutRoute: PathlessLayoutRouteWithChildren,
  AdminRoute: AdminRoute,
  CustomScriptDotjsRoute: CustomScriptDotjsRoute,
  DeferredRoute: DeferredRoute,
  HomeRoute: HomeRoute,
  PostsRoute: PostsRouteWithChildren,
  RedirectRoute: RedirectRoute,
  ReportsRoute: ReportsRoute,
  SignInRoute: SignInRoute,
  SignUpRoute: SignUpRoute,
  UserRoute: UserRoute,
  UsersRoute: UsersRouteWithChildren,
  ApiAssignmentsRoute: ApiAssignmentsRoute,
  ApiUsersRoute: ApiUsersRouteWithChildren,
  AssignmentsAssignmentIdRoute: AssignmentsAssignmentIdRoute,
  DashboardDriveRoute: DashboardDriveRouteWithChildren,
  QuizzesNewRoute: QuizzesNewRoute,
  ShareShareIdRoute: ShareShareIdRoute,
  AssignmentsIndexRoute: AssignmentsIndexRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  QuizzesIndexRoute: QuizzesIndexRoute,
  RoomIndexRoute: RoomIndexRoute,
  ApiAdminStatsRoute: ApiAdminStatsRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiAuthSignInRoute: ApiAuthSignInRoute,
  ApiDriveFoldersRoute: ApiDriveFoldersRouteWithChildren,
  ApiDriveMediaRoute: ApiDriveMediaRouteWithChildren,
  ApiQuizzesMediaRoute: ApiQuizzesMediaRoute,
  ApiRoomRoomIdRoute: ApiRoomRoomIdRoute,
  DashboardClassroomsClassIdRoute: DashboardClassroomsClassIdRoute,
  DashboardClassroomsNewRoute: DashboardClassroomsNewRoute,
  PostsPostIdDeepRoute: PostsPostIdDeepRoute,
  RoomRoomIdIndexRoute: RoomRoomIdIndexRoute,
  ApiShareShareIdQrRoute: ApiShareShareIdQrRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/solid-start'
declare module '@tanstack/solid-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
